// Source: source-materials/Clinic-Pack (1) (1).pdf — "Patients"
//
// Transcribed verbatim from the sample data. No records added, removed, or altered.
// Two patients share the name "James Porter" (555-0102, 555-0103) with different DOBs —
// see D1 in DECISIONS.md for how identity is verified (phone lookup + DOB confirmation).
import type { PatientRecord } from "./types";

export const patients: PatientRecord[] = [
  {
    phone: "555-0101",
    name: "Margaret Hill",
    dob: "1958-02-10",
    insurance: { payer: "Aetna", active: true },
    lastSeen: "2025-09-12",
    assignedProvider: "whitfield",
    flags: [],
  },
  {
    phone: "555-0102",
    name: "James Porter",
    dob: "1971-07-04",
    insurance: { payer: "BlueCross", active: true },
    lastSeen: "2024-11-20",
    assignedProvider: "raman",
    flags: [],
  },
  {
    phone: "555-0103",
    name: "James Porter",
    dob: "1990-03-22",
    insurance: { payer: "UnitedHealthcare", active: true },
    lastSeen: "2023-01-05",
    assignedProvider: null,
    flags: [],
  },
  {
    phone: "555-0104",
    name: "Elena Vasquez",
    dob: "1985-12-01",
    insurance: { payer: "Cigna", active: true },
    lastSeen: "2019-04-10",
    assignedProvider: "whitfield",
    flags: [],
  },
  {
    phone: "555-0105",
    name: "Robert Kim",
    dob: "2010-08-15",
    insurance: { payer: "Aetna", active: true },
    lastSeen: null,
    assignedProvider: null,
    flags: [],
  },
  {
    phone: "555-0106",
    name: "Dana Whitmore",
    dob: "1969-05-30",
    insurance: { payer: "Cigna", active: false },
    lastSeen: "2024-02-18",
    assignedProvider: "crane",
    flags: [],
  },
  {
    phone: "555-0107",
    name: "Harold Stevens",
    dob: "1952-10-09",
    insurance: { payer: "Medicare", active: true },
    lastSeen: "2025-03-01",
    assignedProvider: "crane",
    flags: [],
  },
  {
    phone: "555-0108",
    name: "Patricia Nguyen",
    dob: "1978-06-25",
    insurance: { payer: "Aetna", active: true },
    lastSeen: "2025-12-30",
    assignedProvider: "raman",
    flags: ["discharged"],
  },
  {
    phone: "555-0109",
    name: "Sofia Delgado",
    dob: "1995-09-09",
    insurance: { payer: "Cigna", active: true },
    lastSeen: "2026-05-01",
    assignedProvider: "whitfield",
    flags: [],
  },
  {
    phone: "555-0110",
    name: "George Adams",
    dob: "1948-03-17",
    insurance: { payer: "Medicare", active: true },
    lastSeen: "2024-08-08",
    assignedProvider: "raman",
    flags: [],
  },
  {
    phone: "555-0111",
    name: "Linda Foster",
    dob: "1982-11-11",
    insurance: { payer: "Aetna", active: true },
    lastSeen: "2025-10-10",
    assignedProvider: "whitfield",
    flags: [],
  },
  {
    phone: "555-0112",
    name: "Thomas Wright",
    dob: "1960-07-19",
    insurance: { payer: "Medicare", active: true },
    lastSeen: "2022-12-01",
    assignedProvider: "crane",
    flags: [],
  },
];
